@W-11036662: fix(dependency): Issue of missing javax.validation, hibernate-validator dependencies and version conflict of com.google.cloud:google-cloud-storage while upgrading the spring cloud to Hoxton.SR12 in kork. (#94)
Picked from https://github.com/spinnaker/front50/pull/1119/commits/c37c11949edea2aa6fa7d090f21a1bd38e5355ea

While upgrading spring cloud to Hoxton.SR12, we encountered below errors :

> Task :front50-core:compileJava FAILED
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:31: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:34: error: package org.hibernate.validator.constraints does not exist
import org.hibernate.validator.constraints.URL;
                                          ^
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:44: error: cannot find symbol
@Valid
 ^
  symbol: class Valid
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:60: error: cannot find symbol
  @Valid @Nonnull private List<Release> releases = new ArrayList<>();
   ^
  symbol:   class Valid
  location: class PluginInfo
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:75: error: cannot find symbol
  @URL private String homepage;
   ^
  symbol:   class URL
  location: class PluginInfo
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:201: error: cannot find symbol
    @URL String url;
     ^
  symbol:   class URL
  location: class Repository
front50/front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java:108: error: package javax.validation.constraints does not exist
    @javax.validation.constraints.Pattern(regexp = VERSION_PATTERN)
                                 ^
7 errors

———————————————

> Task :front50-web:compileJava FAILED
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:23: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:24: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Pattern;
                                   ^
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:61: error: cannot find symbol
  PluginInfo upsert(@Valid @RequestBody PluginInfo pluginInfo) {
                     ^
  symbol:   class Valid
  location: class PluginInfoController
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:74: error: cannot find symbol
      @PathVariable String id, @Valid @RequestBody PluginInfo.Release release) {
                                ^
  symbol:   class Valid
  location: class PluginInfoController
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:81: error: cannot find symbol
      @PathVariable String id, @Valid @RequestBody PluginInfo.Release release) {
                                ^
  symbol:   class Valid
  location: class PluginInfoController
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:89: error: cannot find symbol
      @PathVariable @Pattern(regexp = PluginInfo.Release.VERSION_PATTERN) String releaseVersion,
                     ^
  symbol:   class Pattern
  location: class PluginInfoController
front50/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java:99: error: cannot find symbol
      @PathVariable @Pattern(regexp = PluginInfo.Release.VERSION_PATTERN) String releaseVersion) {
                     ^
  symbol:   class Pattern
  location: class PluginInfoController
7 errors

———————————————————

> Task :front50-gcs:compileTestKotlin FAILED
e: /Users/sandeshjain/IdeaProjects/sfcd/front50/front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/FakeStorageRpc.kt: (52, 10): Class 'FakeStorageRpc' is not abstract and does not implement abstract member public abstract fun getCurrentUploadOffset(p0: String!): Long defined in com.google.cloud.storage.spi.v1.StorageRpc

The root cause is missing javax.validation:validation-api and hibernate-validator dependencies, the reason being upgrade of transitive dependency resilience4j from [1.0.0](https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.0.0) to [1.7.0](https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.7.0) while upgrade to Hoxton.SR12.

To fix this issue, we require to explicitly implement the dependency in gradle file of respective module.

The reason for front50-gcs:compileTestKotlin FAILED is version conflict of com.google.cloud:google-cloud-storage:1.113.6 (upgraded as transitive dependency in Hoxton.SR12) versus pinned version of 1.108.0 in front50-gcs.gradle.

To fix this issue, we require strict usage of old version google-cloud-storage (1.108.0) dependency by forcing it in gradle file.