@W-11036662: fix(dependencies): Forcing oci-java-sdk-objectstorage version for desired conflict resolution. (#85)
Picked from https://github.com/spinnaker/front50/pull/1096/commits/5657bd7a0075959c02cfcd631d7ec4d67cf46fca

While enforcing the direct and transitive dependencies strictly from kork-bom using "enforcedPlatform" in build.gradle as:

implementation(enforcedPlatform("io.spinnaker.kork:kork-bom:$korkVersion"))

oci-java-sdk-bom:1.5.17 is overriding the oci-java-sdk-objectstorage:1.19.1 (transitive dependency) version, which is an older version coming from kork-bom mentioned in spinnaker-dependencies.gradle.
It is causing an error in front50-oracle module as given below:

> Task :front50-oracle:compileJava FAILED
/Users/sandeshjain/IdeaProjects/sfcd/front50/front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java:225: error: cannot find symbol
            buildObjectKey(objectType, summary.getName()), summary.getTimeModified().getTime());
                                                                  ^
  symbol:   method getTimeModified()
  location: variable summary of type ObjectSummary
Note: /Users/sandeshjain/IdeaProjects/sfcd/front50/front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

In order to fix, we require oci-java-sdk-objectstorage:1.19.1 to force restore.
Forcing the specified version will take precedence during conflict resolution and provide desired version.